"""empty message

Revision ID: 4d9d339f6e6d
Revises: 20edb61967b2
Create Date: 2017-07-14 23:54:01.692669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9d339f6e6d'
down_revision = '20edb61967b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title', existing_type=sa.String(length=255), type_=sa.Text())
    op.alter_column('posts', 'description', existing_type=sa.String(length=255), type_=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title', existing_type=sa.Text(), type_=sa.String(length=255))
    op.alter_column('posts', 'description', existing_type=sa.Text(), type_=sa.String(length=255))
    # ### end Alembic commands ###
