'''
    LOCAL config file

    please setup next environment variables:
        SQLALCHEMY_DATABASE_URI

'''
DEBUG = True
TESTING = False

JSON_AS_ASCII = False

BCRYPT_LOG_ROUNDS = 4

TOKEN_EXPIRATION_DAYS = 30
TOKEN_EXPIRATION_SECONDS = 0

SECRET_KEY = "SOME_SECRET_KEY"

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:PostGreSQL@localhost:5432/postgres'
SQLALCHEMY_TRACK_MODIFICATIONS = True

PERMANENT_SESSION_LIFETIME = 3600
